#!/bin/bash

# this script will build multi enclave platform's jni.so,
# also compile enclave's edge routine files which was
# generated by enclave sdk toolchain.

# step one: cd make.sh script's path location.

# shellcheck disable=SC2006
this_script_dir=`dirname "$0"`
# shellcheck disable=SC2164
cd "$this_script_dir"

# step two: parse parameters from pom.xml
# parse and store base dir path
export base_dir=$1
# parse and store supported enclave platform set
enclave_platform_config=$2
# process supported enclave platform set
OLD_IFS="$IFS"
IFS=":"
enclave_platform_array=($enclave_platform_config)
IFS="$OLD_IFS"

# shellcheck disable=SC2068
for enclave_platform in ${enclave_platform_array[@]}
do
  echo "$enclave_platform"
  # set "enclave_platform" as TRUE to indicate how
  # to compile jni.so and edge routine
  export "$enclave_platform"=TRUE
done

if [ "$3" == clean ];
then
  # make clean.
  make -f ./Makefile clean
  rm
elif [ "$3" == build ];
then
  # make build.
  make -f ./Makefile build
  # copy jni.so to target/classes, which will be packed into a jar file.
  if [[ $MOCK_IN_SVM == TRUE ]]; then
    cp -r "$base_dir"/src/main/native/bin/platform/mock_in_svm/jni "$base_dir"/target/classes
  fi
else
  echo "unsupported make command!!!"
fi
