/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_confidentialcomputing_enclave_agent_RemoteAttestation */

#ifndef _Included_com_alibaba_confidentialcomputing_enclave_agent_RemoteAttestation
#define _Included_com_alibaba_confidentialcomputing_enclave_agent_RemoteAttestation
#ifdef __cplusplus
extern "C" {
#endif

#define LIBOS_OCCLUM_ENCLAVE_REMOTE_ATTESTATION_GENERATION_SIGNATURE  "([B)Lcom/alibaba/confidentialcomputing/common/EmbeddedLibOSInnerAttestationReport;"
#define LIBOS_OCCLUM_INNER_ATTESTATION_REPORT                         "com/alibaba/confidentialcomputing/common/EmbeddedLibOSInnerAttestationReport"
#define LIBOS_OCCLUM_ENCLAVE_REMOTE_ATTESTATION_EXCEPTION             "com.alibaba.confidentialcomputing.common.exception.ConfidentialComputingException"

#define THROW_EXCEPTION(env, exception, info)                                  \
{                                                                              \
    jclass ra_class = (*env)->FindClass(env, exception);                       \
    if (ra_class == NULL) {                                                    \
        fprintf(stderr, "JavaEnclave Error:  ");                               \
        fprintf(stderr, exception);                                            \
        fprintf(stderr, " class loading failed.\n");                           \
        return;                                                                \
    }                                                                          \
    (*env)->ThrowNew(env, ra_class, info);                                     \
    return;                                                                    \
}

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_agent_RemoteAttestation
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alibaba_confidentialcomputing_enclave_agent_RemoteAttestation_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_agent_RemoteAttestation
 * Method:    generateAttestationReportNative
 * Signature: ([B)Lcom/alibaba/confidentialcomputing/common/agent/EmbeddedLibOSInnerAttestationReport;
 */
JNIEXPORT jobject JNICALL JavaEnclave_TeeLibOSNativeRemoteAttestationGenerate
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif