// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_teaclave_javasdk_enclave_agent_RemoteAttestation */

#ifndef _Included_org_apache_teaclave_javasdk_enclave_agent_RemoteAttestation
#define _Included_org_apache_teaclave_javasdk_enclave_agent_RemoteAttestation
#ifdef __cplusplus
extern "C" {
#endif

#define LIBOS_OCCLUM_ENCLAVE_REMOTE_ATTESTATION_GENERATION_SIGNATURE  "([B)Lorg/apache/teaclave/javasdk/common/EmbeddedLibOSInnerAttestationReport;"
#define LIBOS_OCCLUM_INNER_ATTESTATION_REPORT                         "org/apache/teaclave/javasdk/common/EmbeddedLibOSInnerAttestationReport"
#define LIBOS_OCCLUM_ENCLAVE_REMOTE_ATTESTATION_EXCEPTION             "org/apache/teaclave/javasdk/common/exception/ConfidentialComputingException"

#define THROW_EXCEPTION(env, exception, info)                                  \
{                                                                              \
    jclass ra_class = (*env)->FindClass(env, exception);                       \
    if (ra_class == NULL) {                                                    \
        fprintf(stderr, "Teaclave-java-tee-sdk Error:  ");                     \
        fprintf(stderr, exception);                                            \
        fprintf(stderr, " class loading failed.\n");                           \
        return;                                                                \
    }                                                                          \
    (*env)->ThrowNew(env, ra_class, info);                                     \
    return;                                                                    \
}

/*
 * Class:     org_apache_teaclave_javasdk_enclave_agent_RemoteAttestation
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_teaclave_javasdk_enclave_agent_RemoteAttestation_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_teaclave_javasdk_enclave_agent_RemoteAttestation
 * Method:    generateAttestationReportNative
 * Signature: ([B)Lorg/apache/teaclave/javasdk/common/EmbeddedLibOSInnerAttestationReport;
 */
JNIEXPORT jobject JNICALL JavaEnclave_TeeLibOSNativeRemoteAttestationGenerate
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif