/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper */

#ifndef _Included_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
#define _Included_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
 * Method:    invokeEnclave
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper_invokeEnclave
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
 * Method:    loadService
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper_loadService
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
 * Method:    unloadService
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper_unloadService
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
 * Method:    createIsolate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper_createIsolate__
  (JNIEnv *, jclass);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
 * Method:    createIsolate
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper_createIsolate___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper
 * Method:    destroyIsolate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alibaba_confidentialcomputing_enclave_EnclaveTestHelper_destroyIsolate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
