/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods */

#ifndef _Included_com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods
#define _Included_com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods
 * Method:    isCurveSupported
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods_isCurveSupported
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods
 * Method:    generateECKeyPair
 * Signature: (I[B[B)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods_generateECKeyPair
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods
 * Method:    signDigest
 * Signature: ([B[B[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods_signDigest
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods
 * Method:    verifySignedDigest
 * Signature: ([B[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods_verifySignedDigest
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods
 * Method:    deriveKey
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_confidentialcomputing_enclave_substitutes_NativeSunECMethods_deriveKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
