/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_confidentialcomputing_host_SGXRemoteAttestationVerify */

#include <stdio.h>
#include <stdlib.h>

#include "sgx_urts.h"
#include "sgx_ql_quote.h"
#include "sgx_dcap_quoteverify.h"

#ifndef _Included_com_alibaba_confidentialcomputing_host_SGXRemoteAttestationVerify
#define _Included_com_alibaba_confidentialcomputing_host_SGXRemoteAttestationVerify
#ifdef __cplusplus
extern "C" {
#endif

#define SGX_ENCLAVE_REMOTE_ATTESTATION_VERIFY_SIGNATURE  "([BLcom/alibaba/confidentialcomputing/host/RemoteAttestationVerifyResult;)I"

typedef struct {
    int status;
    int version_check;
    int verify_flag;
} verify_result_wrapper;

/*
 * Class:     com_alibaba_confidentialcomputing_host_SGXRemoteAttestationVerify
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alibaba_confidentialcomputing_host_SGXRemoteAttestationVerify_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     com_alibaba_confidentialcomputing_host_SGXRemoteAttestationVerify
 * Method:    nativeVerifyAttestationReport
 * Signature: ([BLcom/alibaba/confidentialcomputing/host/RemoteAttestationVerifyResult;)I
 */
JNIEXPORT jint JNICALL JavaEnclave_SGX_ENCLAVE_REMOTE_ATTESTATION_VERIFY
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif