/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_confidentialcomputing_host_EmbeddedLibOSEnclave */

#ifndef _Included_com_alibaba_confidentialcomputing_host_EmbeddedLibOSEnclave
#define _Included_com_alibaba_confidentialcomputing_host_EmbeddedLibOSEnclave
#ifdef __cplusplus
extern "C" {
#endif

#define ENCLAVE_CREATING_SIGNATURE         "(IIIILcom/alibaba/confidentialcomputing/host/EmbeddedLibOSEnclaveConfig;Ljava/lang/String;)I"
#define ENCLAVE_CREATING_EXCEPTION         "com/alibaba/confidentialcomputing/host/exception/EnclaveCreatingException"
#define ENCLAVE_DESTROYING_EXCEPTION       "com/alibaba/confidentialcomputing/host/exception/EnclaveDestroyingException"

typedef struct {
    jstring  handler;
    char*    handler_str;
} t_jvm_args;

#define THROW_EXCEPTION(env, exception, info)                                  \
{                                                                              \
    jclass ra_class = (*env)->FindClass(env, exception);                       \
    if (ra_class == NULL) {                                                    \
        fprintf(stderr, "JavaEnclave Error:  ");                               \
        fprintf(stderr, exception);                                            \
        fprintf(stderr, " class loading failed.\n");                           \
        return;                                                                \
    }                                                                          \
    (*env)->ThrowNew(env, ra_class, info);                                     \
    return;                                                                    \
}

/*
 * Class:     com_alibaba_confidentialcomputing_host_EmbeddedLibOSEnclave
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alibaba_confidentialcomputing_host_EmbeddedLibOSEnclave_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     com_alibaba_confidentialcomputing_host_EmbeddedLibOSEnclave
 * Method:    nativeCreateEnclave
 * Signature: (IIIILcom/alibaba/confidentialcomputing/host/EmbeddedLibOSEnclaveConfig;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL JavaEnclave_TeeLibOSNativeCreateEnclave
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jstring);

/*
 * Class:     com_alibaba_confidentialcomputing_host_EmbeddedLibOSEnclave
 * Method:    nativeDestroyEnclave
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL JavaEnclave_TeeLibOSNativeDestroyEnclave
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif